#Requires -Version 5.1
<#
.SYNOPSIS
  RFC-0035: inventory consumers of the legacy mpcvideodec/ffmpeg tree (libavcodec 52 era).

.DESCRIPTION
  Scans src/Source (and related vcxproj) for references that block deleting
  src/Source/filters/transform/mpcvideodec/ffmpeg. Excludes the legacy tree itself
  and the modern island (ffmpeg-modern / modern_ffmpeg adapter sources that talk to
  FFmpeg 8.1 via public headers under the island).

  Writes:
    src/Thirdparty/ffmpeg-modern/mpcvideodec-legacy-ffmpeg-refs.txt
#>
[CmdletBinding()]
param(
  [switch]$FailIfEmpty
)

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..\..')
$scanRoot = Join-Path $repoRoot 'src\Source'
$outFile = Join-Path $repoRoot 'src\Thirdparty\ffmpeg-modern\mpcvideodec-legacy-ffmpeg-refs.txt'

$excludePathFragments = @(
  'filters\transform\mpcvideodec\ffmpeg\',
  'filters\transform\mpcvideodec\modern_ffmpeg\',
  'Thirdparty\ffmpeg-modern\'
)

$patterns = @(
  @{ Name = 'libavcodec_gcc'; Regex = 'libavcodec_gcc' },
  @{ Name = 'mpcvideodec/ffmpeg_include'; Regex = 'mpcvideodec[\\/]+ffmpeg' },
  @{ Name = 'FfmpegContext'; Regex = 'FfmpegContext' },
  @{ Name = 'avcodec_decode_video'; Regex = 'avcodec_decode_video\b' },
  @{ Name = 'avcodec_decode_audio2'; Regex = 'avcodec_decode_audio2?\b' },
  @{ Name = 'avcodec_find_decoder'; Regex = 'avcodec_find_decoder\b' },
  @{ Name = 'avcodec_open'; Regex = 'avcodec_open(2)?\b' },
  @{ Name = 'AVCodecContext'; Regex = '\bAVCodecContext\b' },
  @{ Name = 'RV_FFMPEG'; Regex = '\bRV_FFMPEG\b' },
  @{ Name = 'RA_FFMPEG'; Regex = '\bRA_FFMPEG\b' },
  @{ Name = 'PLAYASA_MPEG2_LEGACY'; Regex = '\bPLAYASA_MPEG2_LEGACY\b' }
)

function Test-ExcludedPath {
  param([string]$FullPath)
  $normalized = $FullPath.Replace('/', '\')
  foreach ($frag in $excludePathFragments) {
    if ($normalized -like "*$frag*") {
      return $true
    }
  }
  return $false
}

$files = Get-ChildItem -Path $scanRoot -Recurse -File -Include *.cpp,*.h,*.c,*.vcxproj,*.vcproj |
  Where-Object { -not (Test-ExcludedPath -FullPath $_.FullName) }

$hits = New-Object System.Collections.Generic.List[object]

foreach ($file in $files) {
  $rel = $file.FullName.Substring($repoRoot.Path.Length).TrimStart('\', '/')
  foreach ($pat in $patterns) {
    $matches = Select-String -Path $file.FullName -Pattern $pat.Regex -ErrorAction SilentlyContinue
    foreach ($m in $matches) {
      $hits.Add([PSCustomObject]@{
          Pattern = $pat.Name
          File = $rel
          Line = $m.LineNumber
          Text = ($m.Line.Trim() -replace '\s+', ' ')
        })
    }
  }
}

$grouped = $hits | Group-Object Pattern | Sort-Object Name
$byFile = $hits | Group-Object File | Sort-Object Count -Descending

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# mpcvideodec-legacy-ffmpeg-refs.txt')
[void]$sb.AppendLine('# Generated by src/BuildScript/audit-rfc0035-legacy-ffmpeg-refs.ps1')
[void]$sb.AppendLine("# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sb.AppendLine('# Scope: src/Source excluding mpcvideodec/ffmpeg and modern_ffmpeg adapter sources')
[void]$sb.AppendLine('#')
[void]$sb.AppendLine("# Total hits: $($hits.Count)")
[void]$sb.AppendLine("# Distinct files: $($byFile.Count)")
[void]$sb.AppendLine('')

[void]$sb.AppendLine('## By pattern')
foreach ($g in $grouped) {
  [void]$sb.AppendLine("$($g.Name): $($g.Count)")
}
[void]$sb.AppendLine('')

[void]$sb.AppendLine('## Top files')
foreach ($g in ($byFile | Select-Object -First 40)) {
  [void]$sb.AppendLine(('{0,5}  {1}' -f $g.Count, $g.Name))
}
[void]$sb.AppendLine('')

[void]$sb.AppendLine('## Hits')
foreach ($h in ($hits | Sort-Object Pattern, File, Line)) {
  $text = if ($h.Text.Length -gt 160) { $h.Text.Substring(0, 160) + '...' } else { $h.Text }
  [void]$sb.AppendLine("$($h.Pattern)`t$($h.File):$($h.Line)`t$text")
}

$outDir = Split-Path -Parent $outFile
if (-not (Test-Path -LiteralPath $outDir)) {
  New-Item -ItemType Directory -Path $outDir | Out-Null
}
Set-Content -LiteralPath $outFile -Value $sb.ToString() -Encoding UTF8

Write-Host "audit-rfc0035-legacy-ffmpeg-refs: wrote $outFile ($($hits.Count) hits, $($byFile.Count) files)"

if ($FailIfEmpty -and $hits.Count -eq 0) {
  throw 'Expected at least one legacy reference while the dual-FFmpeg period is active.'
}

# Gate summary for humans / CI
$blocking = @(
  'MPCVideoDecFilter.cpp',
  'FfmpegContext.c',
  'DXVADecoder',
  'MpaDecFilter',
  'libavcodec_gcc'
)
Write-Host ''
Write-Host 'Blocking themes still present (until RFC-0033 + MpaDec migration):'
foreach ($theme in $blocking) {
  $n = @($hits | Where-Object { $_.File -match $theme -or $_.Text -match $theme -or $_.Pattern -match $theme }).Count
  Write-Host ("  {0,-20} {1}" -f $theme, $n)
}

exit 0
